spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: edge-service
zuul:
#TODO either expose all services from Eureca by default, or uncomment and expose individual using routes
#  ignored-services: '*'
#  ignoredPatterns: /**/api/**
#  routes:
#    auth-service: /auth/**
#    sample-service: /sample/**
#    reservation-service: /reservation/**
#    reservation-client: /client/**
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
#  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DOCKER_IP:192.168.99.100}:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: edge-service
zuul:
#  ignored-services: '*'
#  ignoredPatterns: /**/api/**
#  routes:
#    sample-service: /sample/**
#    user-service: /user/**
security:
  oauth2:
    resource:
      userInfoUri: http://auth-service:8181/uaa/user
#  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
